@startuml

enum CategoriaPrenda{
	ACCESORIOS,
    PARTE_SUPERIOR,
    PARTE_INFERIOR,
    CALZADO
}

enum Material{
	ALGODON,
    LANA,
    SEDA,
    FIBRA_SINTETICA
}

enum TipoPrenda{
    ANTEOJOS
    REMERA_MANGA_CORTA
    PANTALON
    CROCS

}

enum TramaPrenda{
    LISA,
    RAYADA,
    CON_LUNARES,
    A_CUADROS,
    ESTAMPADO
}

class Prenda{
	TipoPrenda tipoPrenda
    Material materialPrenda
    Color colorPrincipal
    Color colorSecundario
    TramaPrenda trama
}

class BorradorPrenda{
    TipoPrenda tipoPrenda
    Material materialPrenda
    Color colorPrincipal
    Color colorSecundario
    TramaPrenda trama

    crearPrenda()
}



Prenda -up-> TipoPrenda
Prenda -up-> Material
Prenda -up-> TramaPrenda
TipoPrenda --> CategoriaPrenda
BorradorPrenda .up.> Prenda
@enduml
