@startuml

enum CategoriaPrenda{
	ACCESORIOS,
    PARTE_SUPERIOR,
    PARTE_INFERIOR,
    CALZADO
}

enum Material{
	ALGODON,
    LANA,
    SEDA,
    FIBRA_SINTETICA
}

enum TipoPrenda{
    ANTEOJOS
    REMERA_MANGA_CORTA
    PANTALON
    CROCS

}

enum TramaPrenda{
    LISA,
    RAYADA,
    CON_LUNARES,
    A_CUADROS,
    ESTAMPADO
}

class Prenda{
	TipoPrenda tipoPrenda
    Material materialPrenda
    Color colorPrincipal
    Color colorSecundario
    TramaPrenda trama
}

class BorradorPrenda{
    TipoPrenda tipoPrenda
    Material materialPrenda
    Color colorPrincipal
    Color colorSecundario
    TramaPrenda trama

    crearPrenda()
}

class Guardarropas{
    String nombre
    List<Prenda> prendasGuardadas
    List<Propuesta> propuestas

    agregarPrenda(Prenda)
    eliminarPrenda(Prenda)
    agregarPropuestaPendiente(Propuesta)
    propuestaRechazada(Propuesta)
    deshacerPropuestasAceptadas()

}

class Usuario{
    List<Guardarropas> misGuardarropas

    crearGuardarropasCompartido(String, Usuario)
    proponerTentativamente(Accion, Prenda, Guardarropas)
    aceptarPropuesta(Propuesta, Guardarropa)
    rechazarPropuesta(Propuesta, Guardarropa)
    deshacerPropuestasAceptadas(Guardarropa)
}

enum Accion{
    AGREGAR
    QUITAR

    getOpuesto()
    realizarAccion(Guardarropa, Prenda)
}

class Propuesta{
    Accion accion
    Prenda prenda
    Boolean fueAceptada

    fueAceptada(Guardarropa)
    getAccionOpuesta()
    getFueAceptada()

}



TipoPrenda <-- Prenda
Prenda -up-> Material
Prenda -up-> TramaPrenda
TipoPrenda --> CategoriaPrenda
BorradorPrenda .up.> Prenda

Guardarropas ->"*" Prenda
Guardarropas -->"*" Propuesta
Propuesta --> Accion
Propuesta -> Prenda
Usuario -->"*" Guardarropas
@enduml
